version: '3'

services:
  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: blog_db_container
    volumes:
      - ./database:/var/lib/postgresql/data